<?php
/**
 * @var $block \Sunarc\OrderStatus\Block\Adminhtml\Order\View\Tab\OrderStatusTab
 */
?>
 
<div class="fieldset-wrapper order-information">
    <div class="fieldset-wrapper-title">
       <span class="title"><?php /* @escapeNotVerified */
           echo __('Order Status History') ?></span>
    </div>

    <?php foreach($block->getOrderStatus() as $item): ?>
        <table class="admin__table-secondary">
            <tbody>
                <tr>
                    <td>
                        <?php echo $block->StatusDateFormat($item['created_at']); ?>  
                    </td>
                    <td> 
                        <?php echo $block->StatusLable($item['status']); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    <?php endforeach; ?>
</div>